version: "3"

services:
  nextjs:
    build: .
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=development
      # Add any other environment variables your app needs
