import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Header from "@/components/header/header";
import BackgroundVideo from "@/components/landing-page/background-video";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Blockbase Landing Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} 
        `}
      >
        <main className="relative w-full  flex flex-col items-center">
          <BackgroundVideo />
          <Header />
          {children}
        </main>
      </body>
    </html>
  );
}
